#!/usr/bin/env python3
"""Offline cleanup of common untranslated Russian phrases in EN sections."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "Libraries/Nmsdk-MotionControlLib/Docs/Components"

HEADING_MAP = {
    "UML-диаграмма классов": "Class Diagram",
    "UML-диаграмма последовательности": "Sequence Diagram",
    "UML-диаграмма состояний": "State Diagram",
    "UML-диаграмма активности": "Activity Diagram",
    "UML-диаграмма компонентов": "Component Diagram",
    "Свойства компонента": "Component Properties",
    "Свойства": "Properties",
    "Методы компонента": "Component Methods",
    "Методы": "Methods",
    "Примеры использования": "Usage Examples",
    "C++ код": "C++ Code",
    "XML конфигурация": "XML Configuration",
    "Связи с конфигурационными проектами": "Project Configuration Links",
    "Использование в конфигурациях": "Usage in Configurations",
    "Источники": "References",
}

REPLACEMENTS = [
    # Labels and headers
    ("**Каталог компонентов:**", "**Component catalog:**"),
    ("**Класс**:", "**Class**:"),
    ("**Регистрация**:", "**Registration**:"),
    ("**Базовый класс**:", "**Base class**:"),
    ("**Назначение**:", "**Purpose**:"),
    ("**Назначение:**", "**Purpose:**"),
    ("**Параметры**:", "**Parameters**:"),
    ("**Параметры:**", "**Parameters:**"),
    ("**Возвращаемое значение**:", "**Return value**:"),
    ("**Возвращаемое значение:**", "**Return value:**"),
    ("**Описание**:", "**Description**:"),
    ("**Описание:**", "**Description:**"),
    ("**Алгоритм:**", "**Algorithm:**"),
    ("**Алгоритм работы ACalculate:**", "**ACalculate algorithm:**"),
    ("**Алгоритм работы:**", "**Algorithm:**"),
    ("**Иерархия наследования:**", "**Inheritance hierarchy:**"),
    ("**Связи с другими компонентами:**", "**Relations with other components:**"),
    ("**Описание жизненного цикла:**", "**Lifecycle description:**"),
    ("**Состояния компонента:**", "**Component states:**"),
    ("**Зависимости:**", "**Dependencies:**"),
    ("**Связи:**", "**Connections:**"),
    ("**Примечание:**", "**Note:**"),
    ("**Важные замечания:**", "**Important notes:**"),
    ("**Связь с другими компонентами:**", "**Relations with other components:**"),
    ("**Принцип работы:**", "**Operating principle:**"),
    ("**Типичные сценарии использования:**", "**Typical usage scenarios:**"),
    ("**Типичные комбинации:**", "**Typical combinations:**"),
    ("**Типичные комбинации с другими компонентами:**", "**Typical combinations with other components:**"),
    ("**Композиция**:", "**Composition**:"),
    ("**Агрегация**:", "**Aggregation**:"),
    ("**Зависимости**:", "**Dependencies**:"),
    ("**Входы**:", "**Inputs**:"),
    ("**Выходы**:", "**Outputs**:"),
    ("**Интерфейсы:**", "**Interfaces:**"),
    ("**Отличия от", "**Differences from"),
    ("**Создание**", "**Creation**"),
    ("**Инициализация (ADefault)**", "**Initialization (ADefault)**"),
    ("**Построение (ABuild)**", "**Build (ABuild)**"),
    ("**Сброс (AReset)**", "**Reset (AReset)**"),
    ("**Вычисление (ACalculate)**", "**Calculation (ACalculate)**"),
    ("См.", "See"),
    ("## Источники", "## References"),
    ("(из ", "(from "),
    (" — базовый класс", " — base class"),
    (" — компонент", " — component"),
    (" — модель", " — model"),
    (" — источник", " — source"),
    (" — эмулятор", " — emulator"),
    (" — приемник", " — receiver"),
    (" — разделитель", " — separator"),
    (" — счетчик", " — counter"),
    (" — элемент", " — element"),
    (" — статистика", " — statistics"),
    # Table headers
    ("| Свойство |", "| Property |"),
    ("| Тип |", "| Type |"),
    ("| Значение по умолчанию |", "| Default |"),
    ("| Описание |", "| Description |"),
    ("| Флаги |", "| Flags |"),
    ("| Назначение |", "| Purpose |"),
    ("| Диапазон |", "| Range |"),
    ("| Источник данных |", "| Data Source |"),
    ("| Изменяется в |", "| Modified In |"),
    # Common mermaid (longest first)
    ("Каждый шаг вычислений", "Each calculation step"),
    ("Создание начальных элементов траектории", "Creating initial trajectory elements"),
    ("Создание начальной структуры", "Creating initial structure"),
    ("Создание нового элемента траектории", "Creating new trajectory element"),
    ("Создание нового блока MultiPC", "Creating new MultiPC block"),
    ("Создание блоков MultiPC", "Creating MultiPC blocks"),
    ("Создание нейронных тренеров", "Creating neural trainers"),
    ("Создание элементов движения", "Creating motion elements"),
    ("Управление элементами движения", "Controlling motion elements"),
    ("Создание нейронов принятия решений", "Creating decision neurons"),
    ("Создание связей между компонентами", "Creating links between components"),
    ("Определение направления движения", "Direction detection"),
    ("Вычисление команд мотонейронов", "Computing motoneuron commands"),
    ("Создание нейросети с параметрической структурой", "Creating neural network with parametric structure"),
    ("Создание MaxCount сом", "Creating MaxCount somas"),
    ("Связывание первых CurCount сом", "Linking first CurCount somas"),
    ("Передача Input на синапсы", "Transfer Input to synapses"),
    ("Чтение входного сигнала", "Reading input signal"),
    ("Вычисление тока на основе входного сигнала", "Computing current based on input signal"),
    ("Сброс тока (Current=0)", "Reset current (Current=0)"),
    ("Инициализация параметров", "Parameter initialization"),
    ("Создание генераторов", "Creating generators"),
    ("Создание связей", "Creating links"),
    ("Создание нейронов", "Creating neurons"),
    ("Создание нейрона", "Creating neuron"),
    ("Создание задержки", "Creating delay"),
    ("Связывание компонентов", "Linking components"),
    ("Генерация последовательностей", "Generating sequences"),
    ("Сравнение через нейрон", "Comparing via neuron"),
    ("Обработка сигналов", "Processing signals"),
    ("Определение направления", "Direction detection"),
    ("Фильтрация сигналов", "Signal filtering"),
    ("Фильтрация по знаку", "Sign filtering"),
    ("Обновление выходов", "Updating outputs"),
    ("Проверка входных свойств", "Checking input properties"),
    ("Обновление выхода", "Updating output"),
    ("Чтение Input", "Reading Input"),
    ("Структура создана", "Structure created"),
    ("Завершение шага", "Step complete"),
    ("После сброса", "After reset"),
    ("Готов к работе", "Ready"),
    ("Готов к вычислениям", "Ready for calculations"),
    ("Готов к вычислениям и обмену данными", "Ready for calculations and data exchange"),
    ("Начало ACalculate", "Start ACalculate"),
    ("Начало ABuild", "Start ABuild"),
    ("Начало потока", "Thread start"),
    ("Конец потока", "Thread end"),
    ("Поток завершён?", "Thread terminated?"),
    ("Поток отправки (SendCommand)", "Send thread (SendCommand)"),
    ("Поток чтения (ReadData)", "Read thread (ReadData)"),
    ("Ожидание 10 мс", "Wait 10 ms"),
    ("DLL загружена?", "DLL loaded?"),
    ("DLL загружена", "DLL loaded"),
    ("DLL загружена<br/>COM-порт открыт<br/>Потоки запущены", "DLL loaded<br/>COM port open<br/>Threads started"),
    ("Время прошло", "Time elapsed"),
    ("Создание", "Creation"),
    ("Уничтожение", "Destroy"),
    ("Начало", "Start"),
    ("Конец", "End"),
    ("Да", "Yes"),
    ("Нет", "No"),
    ("наследуется от", "inherits from"),
    ("использует", "uses"),
    ("создаёт", "creates"),
    ("создает", "creates"),
    ("подключен?", "connected?"),
    ("подключен", "connected"),
    ("подключены", "connected"),
    ("Входной сигнал", "Input signal"),
    ("Входной управляющий сигнал", "Input control signal"),
    ("Выходной ток/сигнал", "Output current/signal"),
    ("Выходной угол", "Output angle"),
    ("Выходная скорость", "Output speed"),
    ("Выходная сила", "Output force"),
    ("Выходное напряжение", "Output voltage"),
    ("Входной угол", "Input angle"),
    ("Входная скорость", "Input speed"),
    ("Входная сила", "Input force"),
    ("Входное перемещение", "Input movement"),
    ("Выходное перемещение", "Output movement"),
    ("Разделенный сигнал", "Separated signal"),
    ("Отрицательная часть", "Negative part"),
    ("Положительная часть", "Positive part"),
    ("Базовые компоненты", "Basic components"),
    ("Элементы движения", "Motion elements"),
    ("Элементы траектории", "Trajectory elements"),
    ("Блоки множественного контроля", "Multi-position control blocks"),
    ("Нейрон сравнения", "Comparison neuron"),
    ("Эталонные генераторы", "Reference generators"),
    ("Тестовые генераторы", "Test generators"),
    ("Файл статистики", "Statistics file"),
    ("Сбор связей", "Collecting links"),
    ("Обработка данных", "Processing data"),
    ("Сохранение в файл", "Saving to file"),
    ("Очистка статистики", "Clearing statistics"),
    ("Обновление времени", "Updating time"),
    ("Проверка ситуации", "Checking situation"),
    ("Новая ситуация?", "New situation?"),
    ("Новая ситуация", "New situation"),
    ("Обучение NeuronTrainer", "Training NeuronTrainer"),
    ("Обновление траектории", "Updating trajectory"),
    ("Создание нового TE", "Creating new TE"),
    ("Создание нового MPC", "Creating new MPC"),
    ("Обновление текущего TE", "Updating current TE"),
    ("Запоминание признаков ситуации", "Storing situation features"),
    ("Импульс начался", "Pulse started"),
    ("Импульс закончился", "Pulse ended"),
    ("Обработка импульса", "Pulse processing"),
    ("Увеличение CurCount", "Increment CurCount"),
    ("Связывание новой сомы", "Linking new soma"),
    ("Создание LTZone", "Creating LTZone"),
    ("Продолжить", "Continue"),
    ("Есть ещё элементы?", "More elements?"),
    ("Есть ещё Inputs?", "More Inputs?"),
    ("Интервал истёк?", "Interval elapsed?"),
    ("доступны?", "available?"),
    ("обучен?", "trained?"),
    # Component intros and descriptions
    ("NEngineMotionControl — движок управления движением", "NEngineMotionControl — motion control engine"),
    ("**Class**: `NEngineMotionControl` — центральный компонент управления движением, объединяющий сенсоры, контроллеры и актуаторы для реализации сложных систем управления движением.", "**Class**: `NEngineMotionControl` — central motion control component combining sensors, controllers, and actuators for implementing complex motion control systems."),
    ("NEngineMotionControl является высокоуровневым компонентом, который создает и управляет сетью элементов движения (NMotionElement), интегрируя импульсные нейросети из Nmsdk-PulseLib с компонентами управления позицией и источниками данных. Компонент поддерживает различные режимы создания сети (CreationMode), адаптивную настройку структуры и управление множественными контурами управления.", "NEngineMotionControl is a high-level component that creates and manages a network of motion elements (NMotionElement), integrating pulse neural networks from Nmsdk-PulseLib with position control components and data sources. The component supports various network creation modes (CreationMode), adaptive structure tuning, and management of multiple control loops."),
    ("NCounterNeuron — счетчик нейрон", "NCounterNeuron — counter neuron"),
    ("**Class**: `NCounterNeuron` — нейрон-счетчик, генерирующий выходной импульс только после получения MaxCount входных импульсов.", "**Class**: `NCounterNeuron` — counter neuron that generates an output pulse only after receiving MaxCount input pulses."),
    ("NCounterNeuron реализует счетчик импульсов, который динамически увеличивает количество активных сом при получении импульсов и генерирует выходной импульс только после достижения MaxCount импульсов.", "NCounterNeuron implements a pulse counter that dynamically increases the number of active somas when receiving pulses and generates an output pulse only after reaching MaxCount pulses."),
    ("NEyeRetina — ретина глаза", "NEyeRetina — eye retina"),
    ("**Class**: `NEyeRetina` — component моделирования биологической ретины глаза для обработки визуальной информации.", "**Class**: `NEyeRetina` — component for modeling the biological eye retina for visual information processing."),
    ("NEyeRetina реализует модель биологической ретины, обрабатывающую входные изображения через слои фоторецепторов (палочки и колбочки).", "NEyeRetina implements a biological retina model that processes input images through photoreceptor layers (rods and cones)."),
    ("NNewMotionElement (NMotionElement) — элемент движения", "NNewMotionElement (NMotionElement) — motion element"),
    ("**Class**: `NMotionElement` (регистрируется как `NNewMotionElement`) — элемент движения, создающий нейросетевую структуру для управления движением.", "**Class**: `NMotionElement` (registered as `NNewMotionElement`) — motion element that creates a neural network structure for motion control."),
    ("NMotionElement является базовым элементом для систем управления движением. Он создает нейросетевую структуру, состоящую из нейронов, генераторов и задержек.", "NMotionElement is the base element for motion control systems. It creates a neural network structure consisting of neurons, generators, and delays."),
    ("NSeqComparison — сравнение последовательностей", "NSeqComparison — sequence comparison"),
    ("**Class**: `NSeqComparison` — component для сравнения последовательностей импульсных сигналов с использованием нейросетевой структуры.", "**Class**: `NSeqComparison` — component for comparing pulse signal sequences using a neural network structure."),
    ("NSeqComparison реализует сравнение последовательностей импульсных сигналов через нейросетевую структуру.", "NSeqComparison implements comparison of pulse signal sequences via a neural network structure."),
    ("NNetworkLinksStatistic — статистика связей сети", "NNetworkLinksStatistic — network link statistics"),
    ("**Class**: `NNetworkLinksStatistic` — component для сбора и сохранения статистики по связям в нейронных сетях.", "**Class**: `NNetworkLinksStatistic` — component for collecting and saving link statistics in neural networks."),
    ("NNetworkLinksStatistic собирает статистику по связям между компонентами в нейронных сетях.", "NNetworkLinksStatistic collects link statistics between components in neural networks."),
    ("**Note:** The component is currently commented out in library registration, но код доступен для использования.", "**Note:** The component is currently commented out in library registration, but the code is available for use."),
    ("NNavMousePrimitive — примитив навигации мыши", "NNavMousePrimitive — mouse navigation primitive"),
    ("**Class**: `NNavMousePrimitive` — component для моделирования навигации мыши в лабиринте с вибриссами (усами) для обнаружения препятствий.", "**Class**: `NNavMousePrimitive` — component for modeling mouse navigation in a maze with whiskers (vibrissae) for obstacle detection."),
    ("NNavMousePrimitive моделирует движение мыши в одномерном лабиринте (полюсе) с использованием вибрисс для обнаружения препятствий.", "NNavMousePrimitive models mouse movement in a one-dimensional maze (pole) using whiskers for obstacle detection."),
    ("NTrajectoryElement — элемент траектории", "NTrajectoryElement — trajectory element"),
    ("**Class**: `NTrajectoryElement` — элемент траектории для построения и следования по траекториям движения, используется в NMazeMemory.", "**Class**: `NTrajectoryElement` — trajectory element for building and following motion trajectories; used in NMazeMemory."),
    ("NTrajectoryElement представляет точку в пространстве траекторий с возможностью перехода к следующим элементам (Forwards).", "NTrajectoryElement represents a point in trajectory space with the ability to transition to next elements (Forwards)."),
    ("NNegSignumSeparator — разделитель отрицательной части сигнала", "NNegSignumSeparator — negative signal component separator"),
    ("NPosSignumSeparator — разделитель положительной части сигнала", "NPosSignumSeparator — positive signal component separator"),
    ("**Class**: `NNegSignumSeparator` — вариант конфигурации `NSignumSeparator` для выделения отрицательной составляющей сигнала.", "**Class**: `NNegSignumSeparator` — configuration variant of `NSignumSeparator` for extracting the negative signal component."),
    ("**Class**: `NPosSignumSeparator` — вариант конфигурации `NSignumSeparator` для выделения положительной составляющей сигнала.", "**Class**: `NPosSignumSeparator` — configuration variant of `NSignumSeparator` for extracting the positive signal component."),
    ("**Base class**: `NSignumSeparator` (вариант конфигурации с `Sign=-1.0`).", "**Base class**: `NSignumSeparator` (configuration variant with `Sign=-1.0`)."),
    ("**Base class**: `NSignumSeparator` (вариант конфигурации с `Sign=1.0`).", "**Base class**: `NSignumSeparator` (configuration variant with `Sign=1.0`)."),
    ("NManipulator — манипулятор", "NManipulator — manipulator"),
    ("**Class**: `NManipulator` — component моделирования манипулятора с электрическими характеристиками.", "**Class**: `NManipulator` — manipulator modeling component with electrical characteristics."),
    ("NManipulator реализует упрощенную модель манипулятора, учитывающую электрические параметры (индуктивность, сопротивление, коэффициент ЭДС).", "NManipulator implements a simplified manipulator model accounting for electrical parameters (inductance, resistance, EMF coefficient)."),
    ("Initialization параметров", "Parameter initialization"),
    ("Calculate тока", "Computing current"),
    ("base class для", "base class for"),
    ("component для", "component for"),
    ("component моделирования", "modeling component"),
    ("физический манипулятор в иерархии управления поведением робота", "physical manipulator in the robot behavior control hierarchy"),
    # Original replacements
    ("используется в проектах, требующих:", "is used in projects that require:"),
    ("Типичные сценарии использования:", "Typical usage scenarios:"),
    ("для тестирования систем управления без физического устройства", "for testing control systems without a physical device"),
    ("для проверки работы контроллеров и алгоритмов управления", "for verifying controller and control algorithm operation"),
    ("для показа работы системы без реального манипулятора", "for demonstrating system operation without a real manipulator"),
    ("Тестирование алгоритмов управления манипулятором", "Testing manipulator control algorithms"),
    ("Отладка систем с обратной связью", "Debugging feedback systems"),
    ("Демонстрационные проекты", "Demonstration projects"),
    ("Обучение работе с системами управления движением", "Training on motion control systems"),
    ("Может подключаться к выходам контроллеров", "Can connect to controller outputs"),
    ("Выходы подключаются к", "Outputs connect to"),
    ("или другим компонентам, требующим входного напряжения", "or other components requiring input voltage"),
    ("Часто используется вместе с", "Often used together with"),
    ("для полной эмуляции манипулятора", "for full manipulator emulation"),
    ("является упрощённой версией для эмуляции", "is a simplified version for emulation"),
    ("Основное отличие - упрощённая логика в", "Main difference — simplified logic in"),
    ("простая передача сигнала", "simple signal passthrough"),
    ("Предназначен для тестирования и отладки, а не для работы с реальным устройством", "Intended for testing and debugging, not for use with a real device"),
    ("для проверки работы контроллеров с синтетическими данными", "for verifying controllers with synthetic data"),
    ("предустановленные значения по умолчанию", "preset default values"),
    ("Может подключаться к выходам моделей манипулятора", "Can connect to manipulator model outputs"),
    ("для обратной связи", "for feedback"),
    ("Разделения сигналов по знаку", "Signal separation by sign"),
    ("когда необходимо обрабатывать только отрицательные значения", "when only negative values need to be processed"),
    ("когда необходимо обрабатывать только положительные значения", "when only positive values need to be processed"),
    ("Управления направлением движения", "Movement direction control"),
    ("для выделения команд движения в противоположном направлении", "for extracting movement commands in the opposite direction"),
    ("для выделения команд движения в одном направлении", "for extracting movement commands in one direction"),
    ("Обработки афферентных сигналов", "Afferent signal processing"),
    ("в системах управления движением для разделения положительных и отрицательных обратных связей", "in motion control systems to separate positive and negative feedback"),
    ("Управление манипулятором с разделением команд для разных направлений", "Manipulator control with command separation for different directions"),
    ("Обработка сигналов ошибки в системах управления", "Error signal processing in control systems"),
    ("Фильтрация сигналов для выделения только отрицательных компонент", "Signal filtering to extract only negative components"),
    ("Фильтрация сигналов для выделения только положительных компонент", "Signal filtering to extract only positive components"),
    ("для полного разделения сигнала", "for complete signal separation"),
    ("Может подключаться к выходам", "Can connect to outputs"),
    ("или других источников сигналов", "or other signal sources"),
    ("Выходы могут подключаться к элементам управления движением", "Outputs can connect to motion control elements"),
    ("Анализа структуры нейронных сетей", "Neural network structure analysis"),
    ("для изучения связей между компонентами", "for studying connections between components"),
    ("Отладки сетей", "Network debugging"),
    ("для проверки корректности связей и весов", "for verifying connection and weight correctness"),
    ("Исследования динамики весов", "Weight dynamics research"),
    ("для отслеживания изменений весов связей во времени", "for tracking connection weight changes over time"),
    ("Документирования сетей", "Network documentation"),
    ("для сохранения структуры сети в файлы", "for saving network structure to files"),
    ("Анализ структуры сложных нейронных сетей управления движением", "Analysis of complex motion control neural networks"),
    ("Отладка систем с множественными связями", "Debugging systems with multiple connections"),
    ("Исследование обучения и адаптации сетей", "Studying network learning and adaptation"),
    ("Сохранение снимков состояния сети для последующего анализа", "Saving network state snapshots for later analysis"),
    ("Подключается к сетям", "Connects to networks"),
    ("через свойство", "via property"),
    ("Анализирует связи внутри подключённых сетей", "Analyzes connections within connected networks"),
    ("Сохраняет результаты в файлы формата INI", "Saves results to INI-format files"),
    ("Компонент в настоящее время закомментирован в регистрации библиотеки", "The component is currently commented out in library registration"),
    ("Большая часть функциональности обработки связей закомментирована в коде", "Most link processing functionality is commented out in the code"),
    ("Требует доработки для полной функциональности", "Requires further development for full functionality"),
    ("Файлы статистики сохраняются в формате INI с именами вида", "Statistics files are saved in INI format with names like"),
    ("Распознавания паттернов", "Pattern recognition"),
    ("для сравнения входных последовательностей с эталонными", "for comparing input sequences with reference ones"),
    ("Классификации сигналов", "Signal classification"),
    ("для определения принадлежности последовательности к определённому классу", "for determining sequence membership in a specific class"),
    ("Оценки сходства", "Similarity assessment"),
    ("для измерения степени совпадения двух последовательностей", "for measuring the degree of match between two sequences"),
    ("Обучения и адаптации", "Learning and adaptation"),
    ("для сравнения текущих последовательностей с запомненными", "for comparing current sequences with stored ones"),
    ("Распознавание траекторий движения", "Movement trajectory recognition"),
    ("Классификация паттернов активности нейронов", "Classification of neuron activity patterns"),
    ("Сравнение эталонных и текущих последовательностей команд", "Comparison of reference and current command sequences"),
    ("Оценка качества обучения нейросетей", "Assessment of neural network training quality"),
    ("Эталонные последовательности (KF) генерируются генераторами", "Reference sequences (KF) are generated by"),
    ("с задержками из", "with delays from"),
    ("Тестовые последовательности (Fr) генерируются генераторами", "Test sequences (Fr) are generated by"),
    ("Оба типа генераторов подключены к соме нейрона: KF → возбуждающие синапсы, Fr → тормозные синапсы", "Both generator types connect to the neuron soma: KF → excitatory synapses, Fr → inhibitory synapses"),
    ("Нейрон сравнивает последовательности через LTZone: если последовательности совпадают, возбуждение от KF превосходит торможение от Fr, и нейрон генерирует выходной импульс", "The neuron compares sequences via LTZone: if sequences match, excitation from KF exceeds inhibition from Fr, and the neuron generates an output pulse"),
    ("— упрощённая ветвящаяся система управления движением.", "— simplified branched motion control system."),
    ("— эмулятор входа манипулятора в иерархии управления.", "— manipulator input emulator in the control hierarchy."),
    ("— эмулятор источника манипулятора в иерархии управления.", "— manipulator source emulator in the control hierarchy."),
    ("— разделитель сигнум-сигналов в контурах управления.", "— signum signal separator in control loops."),
    ("— статистика связей в нейросетевых контурах управления движением.", "— link statistics in neural motion control loops."),
    ("— сравнение последовательностей импульсов в нейронных структурах управления.", "— pulse sequence comparison in neural control structures."),
    ("компонент создаётся через конструктор", "component is created via constructor"),
    ("компонент создается через конструктор", "component is created via constructor"),
    ("подготовка к работе", "preparation for operation"),
    ("наследуется от базового класса", "inherited from base class"),
    ("и сброс состояния", "and state reset"),
    ("передача входного сигнала на выход", "passing input signal to output"),
    ("Имя класса нейрона", "Neuron class name"),
    ("Имя класса генератора", "Generator class name"),
    ("Имя класса задержки", "Delay class name"),
    ("Длительность импульсов (с)", "Pulse duration (s)"),
    ("Амплитуда импульсов", "Pulse amplitude"),
    ("Частота генерации (Гц)", "Generation frequency (Hz)"),
    ("Задержка левого двигателя (с)", "Left engine delay (s)"),
    ("Задержка правого двигателя (с)", "Right engine delay (s)"),
    ("Задержка синхронизации 1 (с)", "Synchronization 1 delay (s)"),
    ("Задержка синхронизации 2 (с)", "Synchronization 2 delay (s)"),
    ("Использовать транзитный сигнал для двигателей", "Use transit signal for engines"),
    ("Использовать транзитный сигнал для синхронизации", "Use transit signal for synchronization"),
    ("Сигнал остановки", "Stop signal"),
    ("Сигнал движения вперед", "Forward movement signal"),
    ("Сигнал движения назад", "Backward movement signal"),
    ("Сигнал поворота влево", "Left turn signal"),
    ("Сигнал поворота вправо", "Right turn signal"),
    ("Передача системам управления", "Transfer to control systems"),
    ("Конструктор компонента", "Component constructor"),
    ("Деструктор компонента", "Component destructor"),
    ("Инициализация значений по умолчанию", "Initialize default values"),
    ("Построение внутренней структуры компонента", "Build internal component structure"),
    ("Сброс состояния компонента", "Reset component state"),
    ("Выполнение вычислений на текущем шаге", "Execute calculations on current step"),
    ("Создание нового экземпляра компонента", "Create new component instance"),
    ("Указатель на новый экземпляр", "Pointer to new instance"),
    ("Все сеттеры свойств обновляют параметры соответствующих генераторов, задержек и нейронов при их существовании.", "All property setters update parameters of corresponding generators, delays, and neurons when they exist."),
    ("используется для определения направления движения объекта управления на основе сигналов двигателей.", "is used to determine control object movement direction based on engine signals."),
    ("генерация команд управления для систем движения", "generating control commands for movement systems"),
    ("Эмуляции входных команд манипулятора", "Manipulator input command emulation"),
    ("Эмуляции состояния манипулятора", "Manipulator state emulation"),
    ("Отладки систем управления", "Control system debugging"),
    ("Демонстрации функциональности", "Functionality demonstration"),
    ("при успехе", "on success"),
    ("при успешной инициализации", "on successful initialization"),
    ("при успешном построении", "on successful build"),
    ("при успешном сбросе", "on successful reset"),
    ("при успешном вычислении", "on successful calculation"),
    ("Нет", "None"),
    ("нейроны", "neurons"),
    ("нейронов", "neurons"),
    ("сом", "somas"),
    ("сомы", "soma"),
    ("но ", "but "),
    ("но код", "but the code"),
    # Batch 2: remaining common EN-section phrases
    ("Обработка афферентных сигналов по диапазонам", "Processing afferent signals by ranges"),
    ("Обработка афферентных сигналов", "Processing afferent signals"),
    ("Обработка range-афферентов", "Processing range afferents"),
    ("Обработка signum-афферентов", "Processing signum afferents"),
    ("Вычисление статистики контуров", "Computing loop statistics"),
    ("Обновление CurrentContourAmplitude", "Updating CurrentContourAmplitude"),
    ("Обновление CurrentContourAverage", "Updating CurrentContourAverage"),
    ("Обновление Statistic", "Updating Statistic"),
    ("Определение переходного процесса", "Determining transient process"),
    ("Получение данных координат", "Getting coordinate data"),
    ("Получение данных от элементов движения", "Getting data from motion elements"),
    ("Получение позиции от элементов движения", "Getting position from motion elements"),
    ("Получение позиции", "Getting position"),
    ("Получение MotionControlElement", "Getting MotionControlElement"),
    ("Вычисление CurrentPosition из LTZone", "Computing CurrentPosition from LTZone"),
    ("Вычисление Delta = TargetPosition - CurrentPosition", "Computing Delta = TargetPosition - CurrentPosition"),
    ("Вычисление PID-управления", "Computing PID control"),
    ("Вычисление динамики маятника", "Computing pendulum dynamics"),
    ("Вычисление динамики:", "Computing dynamics:"),
    ("Вычисление движения тележки:", "Computing cart movement:"),
    ("Вычисление результирующего момента:", "Computing resultant moment:"),
    ("Вычисление углов через фильтр 2-го порядка", "Computing angles via 2nd-order filter"),
    ("Вычисление углов", "Computing angles"),
    ("Вычисление угла:", "Computing angle:"),
    ("Вычисление угловой скорости:", "Computing angular speed:"),
    ("Вычисление момента:", "Computing moment:"),
    ("Вычисление ЭДС:", "Computing EMF:"),
    ("Вычисление коэффициентов:", "Computing coefficients:"),
    ("Вычисление амплитуды контура", "Computing loop amplitude"),
    ("Вычисление среднего значения", "Computing average value"),
    ("Вычисление frequency = 1/PrevPulseStopTime", "Computing frequency = 1/PrevPulseStopTime"),
    ("Вычисление PID:", "Computing PID:"),
    ("Вычисления выполняются нейронами внутри", "Calculations are performed by internal neurons"),
    ("Вычисления", "Calculations"),
    ("Вычисление тока, ЭДС, момента, скорости, угла", "Computing current, EMF, moment, speed, angle"),
    ("Обновление Output", "Updating Output"),
    ("Обновление Results гистограммы", "Updating histogram Results"),
    ("Обновление матрицы Statistic", "Updating Statistic matrix"),
    ("Обновление статистики", "Updating statistics"),
    ("Обновление максимальной амплитуды", "Updating maximum amplitude"),
    ("Обновление предыдущих значений", "Updating previous values"),
    ("Обновление текущего элемента траектории", "Updating current trajectory element"),
    ("Обновление позиции, генерация вибрисс, обработка столкновений", "Updating position, generating whiskers, processing collisions"),
    ("Обнаружение объектов в области", "Detecting objects in area"),
    ("Обнаружение объектов", "Detecting objects"),
    ("Обнаружение импульса", "Detecting pulse"),
    ("Измерение частоты импульсов", "Measuring pulse frequency"),
    ("Измерение частоты", "Measuring frequency"),
    ("Накопление data", "Accumulating data"),
    ("Фильтрация data by диапазону", "Filtering data by range"),
    ("Фильтрация by диапазону", "Filtering by range"),
    ("Разделение по интервалам", "Separation by intervals"),
    ("Разделение by знаку", "Separation by sign"),
    ("Подавление pulses", "Suppressing pulses"),
    ("Подавление pulses in interval [Delay1, Delay2]", "Suppressing pulses in interval [Delay1, Delay2]"),
    ("Оценка signal", "Estimating signal"),
    ("Чтение входных данных", "Reading input data"),
    ("Чтение входов", "Reading inputs"),
    ("Чтение входных сигналов:", "Reading input signals:"),
    ("processing входов", "processing inputs"),
    ("processing pulses, накопление data", "processing pulses, accumulating data"),
    ("Сбор statistics", "Collecting statistics"),
    ("Проверка интервала", "Checking interval"),
    ("Проверка переходного процесса", "Checking transient process"),
    ("Проверка ситуации", "Checking situation"),
    ("Инициализация массивов статистики", "Initializing statistics arrays"),
    ("Инициализация массивов позиций", "Initializing position arrays"),
    ("Инициализация массивов", "Initializing arrays"),
    ("Установка разрешения изображения", "Setting image resolution"),
    ("Установка состояния перехода", "Setting transition state"),
    ("Сброс состояния перехода", "Resetting transition state"),
    ("Вызов AdaptiveTuning", "Calling AdaptiveTuning"),
    ("Удаление старых генераторов", "Deleting old generators"),
    ("Удаление старых neurons", "Deleting old neurons"),
    ("Запоминание состояния", "Storing state"),
    ("Запоминание признаков ситуации", "Storing situation features"),
    ("Генерация вибрисс", "Generating whiskers"),
    ("Генерация VibrissOutput", "Generating VibrissOutput"),
    ("Генерация PainOutput", "Generating PainOutput"),
    ("Конвертация изображения", "Converting image"),
    ("Преобразование данных:", "Converting data:"),
    ("Обработка изображения", "Processing image"),
    ("Обработка палочек:", "Processing rods:"),
    ("Обработка существующих элементов", "Processing existing elements"),
    ("Обработка по Mode", "Processing by Mode"),
    ("Использование существующих элементов", "Using existing elements"),
    ("Использование прямого входа", "Using direct input"),
    ("Использование существующих", "Using existing"),
    ("Связывание моторных neurons", "Linking motoneurons"),
    ("Связывание IntervalSeparator", "Linking IntervalSeparator"),
    ("Связывание SignumSeparator", "Linking SignumSeparator"),
    ("Связывание генераторов", "Linking generators"),
    ("Связывание neurons", "Linking neurons"),
    ("Связь SignalGen -> ZoneNeurons", "Link SignalGen -> ZoneNeurons"),
    ("Разрывание связей генераторов", "Breaking generator links"),
    ("Creation NIntervalSeparator для афферентов", "Creating NIntervalSeparator for afferents"),
    ("Creation NSignumSeparator для афферентов", "Creating NSignumSeparator for afferents"),
    ("Creation NIntervalSeparator", "Creating NIntervalSeparator"),
    ("Creation NSignumSeparator", "Creating NSignumSeparator"),
    ("Creation афферентов для каждого контура", "Creating afferents for each loop"),
    ("Creation интерneurons если включены", "Creating interneurons if enabled"),
    ("Creation MotoneuronL и MotoneuronR", "Creating MotoneuronL and MotoneuronR"),
    ("Creation блоков подавления", "Creating suppression blocks"),
    ("Creation SuppressUnit1", "Creating SuppressUnit1"),
    ("Creation SuppressUnit2", "Creating SuppressUnit2"),
    ("Creation ORNeuron", "Creating ORNeuron"),
    ("Creation нового NTrajectoryElement", "Creating new NTrajectoryElement"),
    ("Creation нового NMultiPositionControl", "Creating new NMultiPositionControl"),
    ("Creation новых neurons", "Creating new neurons"),
    ("Creation NumObj генераторов ClsSpikeFr", "Creating NumObj ClsSpikeFr generators"),
    ("Creation рецепторов", "Creating receptors"),
    ("Creation источников", "Creating sources"),
    ("Creation файла", "Creating file"),
    ("Creation нового TE", "Creating new TE"),
    ("Creation нового MPC", "Creating new MPC"),
    ("Настройка PAC", "PAC setup"),
    ("После настройки", "After tuning"),
    ("После создания", "After creation"),
    ("after очистки", "after clearing"),
    ("Direction detection движения", "Movement direction detection"),
    ("Updating outputs из входов или параметров", "Updating outputs from inputs or parameters"),
    ("Output = результат обнаружения", "Output = detection result"),
    ("Yesнные от источника управления", "Data from control source"),
    ("Данные от источника управления", "Data from control source"),
    ("Фильтр 2-го порядка для оси Y", "2nd-order filter for Y axis"),
    ("Фильтр 2-го порядка для оси Z", "2nd-order filter for Z axis"),
    ("Фильтр 2-го порядка для оси X", "2nd-order filter for X axis"),
    ("Фильтр 2-го порядка", "2nd-order filter"),
    ("Применение gain:", "Applying gain:"),
    ("Изменение размеров массивов:", "Resizing arrays:"),
    ("Изменение размеров массивов", "Resizing arrays"),
    ("Изображение валидно?", "Image valid?"),
    ("Изображение<br/>валидно?", "Image<br/>valid?"),
    ("Размеры совпадают?", "Sizes match?"),
    ("Размеры<br/>совпадают?", "Sizes<br/>match?"),
    ("Нейроны созданы?", "Neurons created?"),
    ("Нейроны<br/>созданы?", "Neurons<br/>created?"),
    ("Имена классов заданы?", "Class names set?"),
    ("Имена классов<br/>заданы?", "Class names<br/>set?"),
    ("Storage существует?", "Storage exists?"),
    ("Storage<br/>существует?", "Storage<br/>exists?"),
    ("StatsInterval достигнут?", "StatsInterval reached?"),
    ("StatsInterval<br/>достигнут?", "StatsInterval<br/>reached?"),
    ("Еще элементы?", "More elements?"),
    ("Еще контуры?", "More loops?"),
    ("Еще Inputs?", "More Inputs?"),
    ("frequency в диапазоне?", "frequency in range?"),
    ("frequency в<br/>диапазоне?", "frequency in<br/>range?"),
    ("input в [MinRange, MaxRange]?", "input in [MinRange, MaxRange]?"),
    ("input в<br/>[MinRange, MaxRange]?", "input in<br/>[MinRange, MaxRange]?"),
    ("Скорость < порог", "Speed < threshold"),
    ("Скорость >= порог", "Speed >= threshold"),
    ("Сложная логика", "Complex logic"),
    ("Режим 5:", "Mode 5:"),
    ("Режим 6:", "Mode 6:"),
    ("Построчная recording", "Line-by-line recording"),
    ("Построчная recording всех data", "Line-by-line recording of all data"),
    ("Поиск min/max в истории", "Finding min/max in history"),
    ("Добавление времени начала импульса", "Adding pulse start time"),
    ("Добавление времени окончания импульса", "Adding pulse end time"),
    ("Добавление ExtrenalMoment", "Adding ExternalMoment"),
    ("Увеличение PulseCounter", "Incrementing PulseCounter"),
    ("Управление генераторами в зависимости от ExternalControl", "Controlling generators depending on ExternalControl"),
    ("Управляющие neurons по контурам", "Control neurons per loops"),
    ("Управляющие neurons", "Control neurons"),
    ("Управляемый генератор", "Controlled generator"),
    ("Афферентные neurons", "Afferent neurons"),
    ("Нейроны принятия решений", "Decision neurons"),
    ("Нейрон принятия решения", "Decision neuron"),
    ("Нейроны действий", "Action neurons"),
    ("Нейрон И", "AND neuron"),
    ("Движок управления", "Control engine"),
    ("Генераторы последовательностей", "Sequence generators"),
    ("Генератор последовательностей", "Sequence generator"),
    ("Выход ганглиозных клеток", "Ganglion cell output"),
    ("Сигнал для нижней мышцы", "Signal for lower muscle"),
    ("Ускорение маятника", "Pendulum acceleration"),
    ("Угол маятника", "Pendulum angle"),
    ("Входное изображение", "Input image"),
    ("Внешний moment", "External moment"),
    ("Вnotшний moment", "External moment"),
    ("Результирующий moment", "Resultant moment"),
    ("Родительские elements", "Parent elements"),
    ("Дочерние elements", "Child elements"),
    ("Обработка изображений", "Image processing"),
    ("with 2 возбуждающими синапсами", "with 2 excitatory synapses"),
    ("с Delay1=Delay11, Delay2=Delay12", "with Delay1=Delay11, Delay2=Delay12"),
    ("с Delay1=Delay21, Delay2=Delay22", "with Delay1=Delay21, Delay2=Delay22"),
    ("с афферентными нейронами", "with afferent neurons"),
    ("для каждого диапазона", "for each range"),
    ("для каждого контура", "for each loop"),
    ("для каждой soma", "for each soma"),
    ("для новой soma", "for a new soma"),
    ("для первых CurCount somas", "for the first CurCount somas"),
    ("для афферентов", "for afferents"),
    ("для оси Y", "for Y axis"),
    ("для оси Z", "for Z axis"),
    ("для оси X", "for X axis"),
    ("в зависимости от Mode", "depending on Mode"),
    ("в зависимости от ExternalControl", "depending on ExternalControl"),
    ("в области", "in area"),
    ("в интервал", "in interval"),
    ("в диапазоне", "in range"),
    ("по диапазонам", "by ranges"),
    ("по интервалам", "by intervals"),
    ("по контурам", "per loops"),
    ("по Mode", "by Mode"),
    ("по знаку", "by sign"),
    ("от элементов движения", "from motion elements"),
    ("от источников", "from sources"),
    ("из LTZone", "from LTZone"),
    ("из входов или параметров", "from inputs or parameters"),
    ("из истории", "from history"),
    ("на основе позиции и VibrissSize", "based on position and VibrissSize"),
    ("на SituationCoords", "on SituationCoords"),
    ("(палочки)", "(rods)"),
    ("(R колбочки)", "(R cones)"),
    ("(G колбочки)", "(G cones)"),
    ("(B колбочки)", "(B cones)"),
    ("(если включен)", "(if enabled)"),
    ("(если включены)", "(if enabled)"),
    ("если включен", "if enabled"),
    ("если включены", "if enabled"),
    ("связан с", "linked to"),
    ("with delays from DelaysClsSpikeFr", "with delays from DelaysClsSpikeFr"),
    ("with другими элементами", "with other elements"),
    ("LinkPM() (если включен)", "LinkPM() (if enabled)"),
    ("LinkRenshow() (если включен)", "LinkRenshow() (if enabled)"),
    ("Reset и выход", "Reset and exit"),
    ("ReCreateFile:", "ReCreateFile:"),
    ("ResizeStats:", "ResizeStats:"),
    ("CreateMotoneurons:", "CreateMotoneurons:"),
    ("CreateAfferents:", "CreateAfferents:"),
    ("CreateInterneurons:", "CreateInterneurons:"),
    ("LinkMotoneurons:", "LinkMotoneurons:"),
    ("текущее время", "current time"),
    ("MotionControlState = -1", "MotionControlState = -1"),
    ("MotionControlState = 1", "MotionControlState = 1"),
    ("MotionControlState = 0", "MotionControlState = 0"),
    ("BackwardSpikeTime =", "BackwardSpikeTime ="),
    ("ForwardSpikeTime =", "ForwardSpikeTime ="),
    ("StopSpikeTime =", "StopSpikeTime ="),
    ("PainState = 1", "PainState = 1"),
    ("NAstaticGyro — аstatic gyroscope", "NAstaticGyro — astatic gyroscope"),
    ("астатического гироскопа", "astatic gyroscope"),
    ("астатический гироскоп", "astatic gyroscope"),
    ("modeling component astatic gyroscope for measurement angles orientation", "modeling component for measuring orientation angles"),
    ("implements model astatic gyroscope, which computes angles orientation", "implements an astatic gyroscope model that computes orientation angles"),
    ("Reset angles and internal переменных", "Reset angles and internal variables"),
    ("internal переменных", "internal variables"),
    ("переменных", "variables"),
    ("NEngineControlRangeAfferent — аfferent controller (range)", "NEngineControlRangeAfferent — afferent controller (range)"),
    ("NEngineControlSignumAfferent — аfferent controller (signum)", "NEngineControlSignumAfferent — afferent controller (signum)"),
    ("variant controller motion on базе range-afferents", "motion controller variant based on range afferents"),
    ("variant controller motion on базе signum-features", "motion controller variant based on signum features"),
    ("specialized version of NEngineMotionControl, configured for operation with range-afferents", "specialized version of NEngineMotionControl configured for range afferents"),
    ("specialized version of NEngineMotionControl, configured for operation with signum-afferents", "specialized version of NEngineMotionControl configured for signum afferents"),
    ("Control with range-afferents", "Control with range afferents"),
    ("Control with signum-afferents", "Control with signum afferents"),
    ("using signal separation by ranges", "using signal separation by ranges"),
    ("using signal separation by sign", "using signal separation by sign"),
    ("Granular processing", "Granular processing"),
    ("Simplified processing", "Simplified processing"),
    ("IntervalSeparators", "IntervalSeparators"),
    ("Separators by ranges", "Separators by ranges"),
    ("Separators by sign", "Sign separators"),
    ("Minimum values afferents per loops", "Minimum afferent values per loop"),
    ("Maximum values afferents per loops", "Maximum afferent values per loop"),
    ("Mode расчета ranges", "Range calculation mode"),
    ("Минимальные values afferents by loopм", "Minimum afferent values per loop"),
    ("Максимальные values afferents by loopм", "Maximum afferent values per loop"),
    ("Минимальные", "Minimum"),
    ("Максимальные", "Maximum"),
    ("Масса manipulator", "Manipulator mass"),
    ("Масса", "Mass"),
    ("Внешний", "External"),
    ("Вnotшний", "External"),
    ("Результирующий", "Resultant"),
    ("результирующего", "resultant"),
    ("результирующий", "resultant"),
    ("гравитационного", "gravitational"),
    ("гравитационного moment", "gravitational moment"),
    ("гравитации", "gravity"),
    ("гироскопических", "gyroscopic"),
    ("эффектов", "effects"),
    ("компьютинг", "computing"),
    ("Calculation выполняются neurons", "Calculations are performed by neurons"),
    ("выполняются", "are performed"),
    ("выполняется", "is performed"),
    ("update Output with историей", "update Output with history"),
    ("историей", "history"),
    ("истории", "history"),
    ("гистограммы", "histogram"),
    ("гистограмма", "histogram"),
    ("Гистограмма", "Histogram"),
    ("update with историей", "update with history"),
    ("Начать с", "Start with"),
    ("Генерировать выход после", "Generate output after"),
    ("активной soma", "active soma"),
    ("активных somas", "active somas"),
    ("достижения", "reaching"),
    ("достижении", "reaching"),
    ("specified count pulses", "specified pulse count"),
    ("counting input pulses before generating output", "counting input pulses before generating output"),
    ("generation signal when reaching threshold", "generating signal when reaching threshold"),
    ("Threshold detectors", "Threshold detectors"),
    ("Counting pulses", "Counting pulses"),
    ("pulse sources", "pulse sources"),
    ("sources pulses", "pulse sources"),
    ("See RU section", "See RU section"),
    ("Similarly NEngineMotionControl", "Same as NEngineMotionControl"),
    ("Same as NEngineMotionControl, but with CreationMode=0", "Same as NEngineMotionControl, but with CreationMode=0"),
    ("Uses parameters NEngineMotionControl", "Uses NEngineMotionControl parameters"),
    ("is created via NEngineMotionControl", "is created via NEngineMotionControl"),
    ("CreationMode = 0 (Signum)", "CreationMode = 0 (Signum)"),
    ("Setting CreationMode = 0", "Setting CreationMode = 0"),
    ("Signum mode", "Signum mode"),
    ("Range mode", "Range mode"),
    ("CreationMode=0", "CreationMode=0"),
    ("CreationMode=1", "CreationMode=1"),
    ("AfferentMin", "AfferentMin"),
    ("AfferentMax", "AfferentMax"),
    ("AfferentRangeMode", "AfferentRangeMode"),
    ("более детальная", "more detailed"),
    ("более детальная processing", "more detailed processing"),
    ("Гранулярная", "Granular"),
    ("Гранулярonя", "Granular"),
    ("usageм", "using"),
    ("with usageм", "using"),
    ("с usageм", "using"),
    ("разделения", "separation"),
    ("разделение", "separation"),
    ("разделения signals", "signal separation"),
    ("separation signals", "signal separation"),
    ("separating signals", "separating signals"),
    ("объект control", "control object"),
    ("object control", "control object"),
    ("systems control movement", "motion control systems"),
    ("system control movement", "motion control system"),
    ("control movement", "motion control"),
    ("movement control", "movement control"),
    ("motion control systems", "motion control systems"),
    ("motion control system", "motion control system"),
    ("data about", "data about"),
    ("about with", "about"),
    ("withaboutwiththenянandand", "state"),
    ("withabout", "about"),
    ("thenянandand", "state"),
    ("aboutб", "about"),
    ("об", "about"),
    ("т.д.", "etc."),
    ("и т.д.", "etc."),
    ("и т.п.", "etc."),
    ("Н·м", "N·m"),
    ("Нм", "N·m"),
    ("кг", "kg"),
    ("рад/с", "rad/s"),
    ("Гн", "H"),
    ("Ом", "Ω"),
    ("с)", "s)"),
    ("(с)", "(s)"),
    ("(Гц)", "(Hz)"),
    ("(градусы)", "(degrees)"),
    ("(радианы)", "(radians)"),
    ("(нормализовано)", "(normalized)"),
    ("(отладка)", "(debug)"),
    ("(debug)", "(debug)"),
    ("Низкопороговая зона", "Low-threshold zone"),
    ("Участки мембраны", "Membrane sections"),
    ("Возбуждающий генератор", "Excitatory generator"),
    ("Тормозной генератор", "Inhibitory generator"),
    ("Имя класса участка мембраны", "Membrane section class name"),
    ("Имя класса низкопороговой зоны", "Low-threshold zone class name"),
    ("Имя класса возбуждающего генератора", "Excitatory generator class name"),
    ("Имя класса тормозного генератора", "Inhibitory generator class name"),
    ("Максимальное количество pulses для генерации выхода", "Maximum pulse count to generate output"),
    ("Текущее количество активных somas (начальное значение)", "Current active soma count (initial value)"),
    ("Входной импульсный сигнал", "Input pulse signal"),
    ("Другие компоненты систем", "Other system components"),
    ("Вектор участков мембраны (somas)", "Vector of membrane sections (somas)"),
    ("Предыдущее количество somas", "Previous soma count"),
    ("Флаг активного импульса", "Active pulse flag"),
    ("Построение внутренней структуры", "Build internal structure"),
    ("Передает Input на синапсы", "Transfers Input to synapses"),
    ("Отслеживает начало и окончание pulses", "Tracks pulse start and end"),
    ("При окончании импульса увеличивает CurCount", "When a pulse ends, increments CurCount"),
    ("и связывает новую soma", "and links a new soma"),
    ("Создает связи между каналами soma", "Creates links between soma channels"),
    ("обратной связью", "feedback"),
    ("Creation links для soma", "Creating links for soma"),
    ("указатель на soma", "pointer to soma"),
    ("Creation нового экземпляра", "Creating new instance"),
    ("Указатель на новый экземпляр", "Pointer to new instance"),
    ("используется для подсчета pulses", "is used for counting pulses"),
    ("генерации выходного сигнала", "generating output signal"),
    ("Подсчет pulses", "Counting pulses"),
    ("подсчет input pulses", "counting input pulses"),
    ("Пороговые детекторы", "Threshold detectors"),
    ("подсчет pulses от источников", "counting pulses from sources"),
    ("Преобразованные data", "Converted data"),
    ("Преобразованные", "Converted"),
    ("Преобразование", "Conversion"),
    ("преобразование", "conversion"),
    ("преобразует", "converts"),
    ("преобразует его", "converts it"),
    ("его в", "it to"),
    ("его ", "it "),
    ("Читает input signal", "Reads input signal"),
    ("обновляет output", "updates output"),
    ("Подключение к контроллеру", "Connecting to controller"),
    ("Подключение к", "Connecting to"),
    ("Подключение", "Connection"),
    ("подключение", "connection"),
    ("Автоматически инициализируется", "Automatically initialized"),
    ("Автоматически is initialized", "Automatically initialized"),
    ("Автоматически", "Automatically"),
    ("инициализируется нулями", "initialized to zeros"),
    ("initialized to zeros", "initialized to zeros"),
    ("initialized нулями", "initialized to zeros"),
    ("нулями", "to zeros"),
    ("Flag is necessaryности update output", "Flag indicating output update is required"),
    ("is necessaryности", "indicating"),
    ("necessaryности", "required"),
    ("Transfer manipulatorу", "Transfer to manipulator"),
    ("manipulatorу", "manipulator"),
    ("manipulatorом", "manipulator"),
    ("connectedandя", "connection"),
    ("connectedandя to", "connection to"),
    ("wheninaboutдам", "actuators"),
    ("упраinляющandй", "control"),
    ("упраinляющегabout", "control"),
    ("гfromaboutin", "ready"),
    ("to calculationм", "for calculations"),
    ("calculationм", "calculations"),
    ("andндуtoтandinнaboutwithтand", "inductance"),
    ("accounting for andндуtoтandinнaboutwithтand", "accounting for inductance"),
    ("formula with accounting for", "formula accounting for"),
    ("coefficient EMF). Component computes", "EMF coefficient). The component computes"),
    ("computes current based on input control signal and outputs", "computes current from the input control signal and outputs"),
    ("for connectedandя to", "for connection to"),
    ("receives control signal from", "receives control signal from"),
    ("provides current/signal control for", "provides current/control signal for"),
]

# Sort longest first to avoid partial replacements
REPLACEMENTS.sort(key=lambda x: -len(x[0]))


def apply_heading_map(text: str) -> str:
    for ru, en in HEADING_MAP.items():
        text = re.sub(rf"^## {re.escape(ru)}\s*$", f"## {en}", text, flags=re.M)
        text = re.sub(rf"^### {re.escape(ru)}\s*$", f"### {en}", text, flags=re.M)
    return text


def fix_file(path: Path) -> int:
    content = path.read_text(encoding="utf-8")
    en_m = re.search(r"^## EN\s*$", content, re.M)
    if not en_m:
        return 0
    en = content[en_m.end():]
    original = en
    en = apply_heading_map(en)
    for ru, en_phrase in REPLACEMENTS:
        en = en.replace(ru, en_phrase)
    if en != original:
        content = content[: en_m.end()] + en
        path.write_text(content, encoding="utf-8")
        return 1
    return 0


def main() -> None:
    files = sorted(DOCS_DIR.glob("*.md"))
    fixed = 0
    for path in files:
        if path.name in ("README.md", "ManipulatorsAndMotion.md"):
            continue
        if fix_file(path):
            fixed += 1
    print(f"Offline cleanup done, updated {fixed} files")


if __name__ == "__main__":
    main()
