cmake_minimum_required(VERSION 3.16)

# Integration tests
add_subdirectory(ComponentSystem)
add_subdirectory(PropertyConnections)
add_subdirectory(Serialization)
add_subdirectory(Libraries)
add_subdirectory(HardwareLib)
add_subdirectory(Migration)
add_subdirectory(GUI)
add_subdirectory(ConfigValidation)

