# Unified Boost discovery for Nmsdk (vcpkg MODULE mode, Linux CONFIG, manual fallback).
include_guard(GLOBAL)

if(TARGET Nmsdk::Boost)
  return()
endif()

set(_NMSDK_BOOST_COMPONENTS program_options thread filesystem system chrono atomic)

if(NOT Boost_FOUND)
  if(UNIX AND NOT APPLE)
    set(_nmsdk_boost_config_ok TRUE)
    foreach(_comp IN LISTS _NMSDK_BOOST_COMPONENTS)
      if(NOT TARGET boost_${_comp} AND NOT TARGET Boost::${_comp})
        find_package(boost_${_comp} CONFIG QUIET)
      endif()
      if(NOT TARGET boost_${_comp} AND NOT TARGET Boost::${_comp})
        set(_nmsdk_boost_config_ok FALSE)
      endif()
    endforeach()
    if(_nmsdk_boost_config_ok)
      set(Boost_FOUND TRUE)
    else()
      find_package(Boost CONFIG QUIET COMPONENTS ${_NMSDK_BOOST_COMPONENTS})
    endif()
  endif()
  if(NOT Boost_FOUND)
    find_package(Boost QUIET COMPONENTS ${_NMSDK_BOOST_COMPONENTS})
  endif()
endif()

add_library(Nmsdk_Boost INTERFACE)
add_library(Nmsdk::Boost ALIAS Nmsdk_Boost)

set(_nmsdk_boost_linked FALSE)
foreach(_comp IN LISTS _NMSDK_BOOST_COMPONENTS)
  if(TARGET Boost::${_comp})
    target_link_libraries(Nmsdk_Boost INTERFACE Boost::${_comp})
    set(_nmsdk_boost_linked TRUE)
  elseif(TARGET boost_${_comp})
    target_link_libraries(Nmsdk_Boost INTERFACE boost_${_comp})
    set(_nmsdk_boost_linked TRUE)
  endif()
endforeach()

if(NOT _nmsdk_boost_linked AND Boost_FOUND AND Boost_LIBRARIES)
  target_link_libraries(Nmsdk_Boost INTERFACE ${Boost_LIBRARIES})
  if(Boost_INCLUDE_DIRS)
    target_include_directories(Nmsdk_Boost INTERFACE ${Boost_INCLUDE_DIRS})
  endif()
  set(_nmsdk_boost_linked TRUE)
endif()

if(NOT _nmsdk_boost_linked)
  find_path(_NMSDK_BOOST_INCLUDE_DIR boost/version.hpp
    PATHS /usr/include /usr/local/include)
  set(_NMSDK_BOOST_LIBS "")
  foreach(_comp IN LISTS _NMSDK_BOOST_COMPONENTS)
    string(TOUPPER ${_comp} _comp_upper)
    find_library(_NMSDK_BOOST_LIB_${_comp_upper}
      NAMES boost_${_comp}
      PATHS /usr/lib /usr/local/lib /usr/lib/x86_64-linux-gnu)
    if(_NMSDK_BOOST_LIB_${_comp_upper})
      list(APPEND _NMSDK_BOOST_LIBS ${_NMSDK_BOOST_LIB_${_comp_upper}})
    endif()
  endforeach()
  if(_NMSDK_BOOST_INCLUDE_DIR AND _NMSDK_BOOST_LIBS)
    target_include_directories(Nmsdk_Boost INTERFACE ${_NMSDK_BOOST_INCLUDE_DIR})
    target_link_libraries(Nmsdk_Boost INTERFACE ${_NMSDK_BOOST_LIBS})
    set(_nmsdk_boost_linked TRUE)
    message(STATUS "Boost found via manual library lookup")
  endif()
endif()

if(NOT _nmsdk_boost_linked)
  message(FATAL_ERROR
    "Boost (program_options, thread, filesystem, system, chrono, atomic) not found. "
    "On Ubuntu/Debian install: sudo apt install libboost-all-dev")
endif()

if(Boost_VERSION)
  message(STATUS "Nmsdk Boost ${Boost_VERSION}")
else()
  message(STATUS "Nmsdk Boost linked (${_NMSDK_BOOST_COMPONENTS})")
endif()
